language: python

# for container-y goodness:
sudo: false

python:
  - "3.6"
  - "2.7"

# command to install dependencies
install:
- "pip install --upgrade pip setuptools"
- "pip install -Ue .[test]"

# command to run tests, e.g. python setup.py test
script: coverage run --source mailinglogger -m pytest

after_success:
  - coveralls

jobs:
  include:

    - stage: coverage
      if: type != cron
      python: 3.6
      after_success: skip

      install: "pip install -U coveralls-check"
      script: "coveralls-check $TRAVIS_COMMIT"

    - stage: release
      if: tag IS present
      python: 3.6
      script: skip
      # work around https://github.com/travis-ci/travis-ci/issues/8337:
      after_success: true

      install:
      - "pip install --upgrade pip setuptools"
      - "pip install -Ue .[build]"
      deploy:
        provider: pypi
        user: chrisw
        password:
          secure: C1eX1FigupxF5iQfgKWbYKdmio+NgsxG9IvDzY8dXQt6ORSrYS0l5//L/hyHVwK0Y4Evt41rNodDngc5p7XK31cfBTyPSRY80KV4MtIPGdJQdk3J/L12JnemQR2RN+qJRjG39ehZdGlPAPtMrlrbpbbRa9zf3QD5+9UZPHHtde0=
        on:
          tags: true
          repo: Simplistix/mailinglogger
        skip_cleanup: true
        distributions: "sdist bdist_wheel"
